server {
    listen 80;
    server_name inventory.qrtably.com;

    location = /favicon.ico { access_log off; log_not_found off; }
    
    # مسار الملفات الثابتة (Static Files)
    location /static/ {
        alias /root/found-inventory/found-inventory-1/staticfiles/;
    }

    # مسار ملفات الميديا (تم تعطيله لأننا نخدم الملفات عبر Django مباشرة لتجنب مشاكل المسارات)
    # location /media/ {
    #    alias /root/found-inventory/found-inventory-1/media/;
    # }

    location / {
        include proxy_params;
        proxy_pass http://unix:/run/gunicorn.sock;
    }
}
