# Generated by Django 4.2.7 on 2026-01-23 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0033_securebackup_delete_aiinsightlog_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='container',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='inventory_app.container'),
        ),
    ]
